# todo-app-service.yaml (Activity 5)
apiVersion: v1
kind: Service
metadata:
  name: secret-todo-app-service
spec:
  type: NodePort
  selector:
    app: secret-todo-app # Must match the Deployment's label
  ports:
  - protocol: TCP
    port: 3000          # Service port (internal)
    targetPort: 3000    # Container port
    nodePort: 31010     # External port as required by the challenge